#!/usr/bin/env python3
"""Upload the generated Tonight index JSON into Firestore.

Usage:
  python scripts/upload_tonight_index_to_firestore.py \
      --input assets/data/tonight_kaggle_index.json \
      --collection tonight_index_entries_v1 \
      --manifest-collection tonight_index_manifest \
      --manifest-doc current

Prerequisites:
  - pip install firebase-admin
  - Set FIREBASE_SERVICE_ACCOUNT_JSON to a service-account JSON file path
"""

from __future__ import annotations

import argparse
import json
import os
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        default="assets/data/tonight_kaggle_index.json",
        help="Path to index JSON generated by build_tonight_kaggle_index.py",
    )
    parser.add_argument(
        "--collection",
        default="tonight_index_entries_v1",
        help="Firestore collection for index entries.",
    )
    parser.add_argument(
        "--manifest-collection",
        default="tonight_index_manifest",
        help="Firestore collection for index manifest docs.",
    )
    parser.add_argument(
        "--manifest-doc",
        default="current",
        help="Manifest document id.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=350,
        help="Write batch size (max 500).",
    )
    parser.add_argument(
        "--max-entries",
        type=int,
        default=0,
        help="Optional cap for quick dry-runs.",
    )
    parser.add_argument(
        "--start-index",
        type=int,
        default=0,
        help="Start uploading from this entry index to resume partial uploads.",
    )
    parser.add_argument(
        "--commit-delay-ms",
        type=int,
        default=120,
        help="Delay between batch commits to avoid write-rate quota bursts.",
    )
    parser.add_argument(
        "--retry-max-attempts",
        type=int,
        default=8,
        help="Max retry attempts for RESOURCE_EXHAUSTED batches.",
    )
    parser.add_argument(
        "--skip-manifest",
        action="store_true",
        help="Skip writing manifest (recommended for partial/resume uploads).",
    )
    args = parser.parse_args()

    input_path = Path(args.input)
    if not input_path.exists():
        raise FileNotFoundError(f"Input index file not found: {input_path}")

    entries = _load_entries(input_path, max_entries=args.max_entries)
    if not entries:
        raise RuntimeError("No entries found to upload.")

    db = _init_firestore()
    _upload_entries(
        db=db,
        entries=entries,
        collection=args.collection,
        batch_size=args.batch_size,
        start_index=args.start_index,
        commit_delay_ms=args.commit_delay_ms,
        retry_max_attempts=args.retry_max_attempts,
    )
    if args.skip_manifest or args.max_entries > 0 or args.start_index > 0:
        print("Manifest update skipped for partial/resume upload.")
    else:
        _write_manifest(
            db=db,
            collection=args.collection,
            manifest_collection=args.manifest_collection,
            manifest_doc=args.manifest_doc,
            total_count=len(entries),
            source_file=input_path,
        )

    print(
        f"Upload complete. {len(entries)} entries written to collection '{args.collection}'."
    )


def _init_firestore():
    service_account = os.environ.get("FIREBASE_SERVICE_ACCOUNT_JSON", "").strip()
    if not service_account:
        raise RuntimeError(
            "Set FIREBASE_SERVICE_ACCOUNT_JSON to your Firebase service-account JSON path."
        )
    if not Path(service_account).exists():
        raise FileNotFoundError(
            f"FIREBASE_SERVICE_ACCOUNT_JSON path does not exist: {service_account}"
        )

    try:
        import firebase_admin
        from firebase_admin import credentials, firestore
    except Exception as exc:
        raise RuntimeError(
            "firebase-admin package is required. Install with: pip install firebase-admin"
        ) from exc

    if not firebase_admin._apps:
        cred = credentials.Certificate(service_account)
        firebase_admin.initialize_app(cred)

    return firestore.client()


def _load_entries(path: Path, *, max_entries: int = 0) -> List[Dict[str, Any]]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    raw_entries = payload.get("entries")
    if not isinstance(raw_entries, list):
        raise RuntimeError("Invalid index format: 'entries' must be a list.")

    entries: List[Dict[str, Any]] = []
    for idx, raw in enumerate(raw_entries):
        if max_entries > 0 and idx >= max_entries:
            break
        if not isinstance(raw, dict):
            continue

        entry_id = _to_int(raw.get("id"))
        media_type = str(raw.get("mediaType", "")).strip().lower()
        title = str(raw.get("title", "")).strip()
        if entry_id is None or entry_id <= 0 or media_type not in {"movie", "tv"}:
            continue
        if not title:
            continue

        moods = raw.get("moods")
        if not isinstance(moods, list):
            moods = []

        entries.append(
            {
                "id": entry_id,
                "mediaType": media_type,
                "title": title,
                "originalLanguage": _nullable_str(raw.get("originalLanguage")),
                "runtimeMinutes": _to_int(raw.get("runtimeMinutes")),
                "voteAverage": _to_float(raw.get("voteAverage")),
                "voteCount": _to_int(raw.get("voteCount")) or 0,
                "popularity": _to_float(raw.get("popularity")) or 0.0,
                "moods": [str(x).strip() for x in moods if str(x).strip()],
                "releaseDate": _nullable_str(raw.get("releaseDate")),
                "updatedAt": datetime.now(timezone.utc),
            }
        )

    return entries


def _upload_entries(
    *,
    db,
    entries: Iterable[Dict[str, Any]],
    collection: str,
    batch_size: int,
    start_index: int,
    commit_delay_ms: int,
    retry_max_attempts: int,
) -> None:
    if batch_size <= 0 or batch_size > 500:
        raise ValueError("batch-size must be between 1 and 500")

    entries_list = list(entries)
    total = len(entries_list)
    if start_index < 0 or start_index > total:
        raise ValueError("start-index is out of range")

    if commit_delay_ms < 0:
        raise ValueError("commit-delay-ms must be >= 0")

    written = 0

    for start in range(start_index, total, batch_size):
        chunk = entries_list[start : start + batch_size]
        batch = db.batch()
        for entry in chunk:
            doc_id = f"{entry['mediaType']}_{entry['id']}"
            doc_ref = db.collection(collection).document(doc_id)
            batch.set(doc_ref, entry)
        _commit_with_retries(batch, max_attempts=retry_max_attempts)
        written += len(chunk)
        uploaded_absolute = start_index + written
        if uploaded_absolute % 10000 == 0 or uploaded_absolute == total:
            print(f"Wrote {uploaded_absolute}/{total} entries")
        if commit_delay_ms > 0:
            time.sleep(commit_delay_ms / 1000)


def _commit_with_retries(batch, *, max_attempts: int) -> None:
    # Delayed import keeps this script import-light when not uploading.
    from google.api_core.exceptions import ResourceExhausted

    attempt = 0
    while True:
        try:
            batch.commit()
            return
        except ResourceExhausted:
            attempt += 1
            if attempt >= max_attempts:
                raise
            sleep_seconds = min(2 ** attempt, 45)
            print(
                f"RESOURCE_EXHAUSTED on batch commit, retry {attempt}/{max_attempts} "
                f"after {sleep_seconds}s",
            )
            time.sleep(sleep_seconds)


def _write_manifest(
    *,
    db,
    collection: str,
    manifest_collection: str,
    manifest_doc: str,
    total_count: int,
    source_file: Path,
) -> None:
    manifest = {
        "collection": collection,
        "totalCount": total_count,
        "sourceFile": str(source_file),
        "updatedAt": datetime.now(timezone.utc),
        "version": 1,
    }
    db.collection(manifest_collection).document(manifest_doc).set(manifest)


def _to_int(value: Any):
    if isinstance(value, int):
        return value
    if isinstance(value, float):
        return int(value)
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return int(float(text))
    except Exception:
        return None


def _to_float(value: Any):
    if isinstance(value, float):
        return value
    if isinstance(value, int):
        return float(value)
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    try:
        return float(text)
    except Exception:
        return None


def _nullable_str(value: Any):
    if value is None:
        return None
    text = str(value).strip()
    return text or None


if __name__ == "__main__":
    main()
